services:
    phpbb.pages.listener:
        class: phpbb\pages\event\listener
        arguments:
            - @controller.helper
            - @phpbb.pages.operator
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }
