imports:
    - { resource: tables.yml }

services:
    phpbb.pages.listener:
        class: phpbb\pages\event\listener
        tags:
            - { name: event.listener }

    phpbb.pages.entity:
        class: phpbb\pages\entity\page
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.pages%
