imports:
    - { resource: tables.yml }

services:
    phpbb.pages.listener:
        class: phpbb\pages\event\listener
        arguments:
            - @auth
            - @controller.helper
            - @phpbb.pages.operator
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    phpbb.pages.entity:
        class: phpbb\pages\entity\page
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.pages%
