services:
    phpbb.pages.listener:
        class: phpbb\pages\event\listener
        tags:
            - { name: event.listener }

    phpbb.pages.operator:
        class: phpbb\pages\operators\page
        arguments:
            - @service_container
            - @dbal.conn
            - @ext.manager
            - %tables.pages%
            - %tables.pages_links%
            - %tables.pages_pages_links%
