services:
    phpbb.pages.listener:
        class: phpbb\pages\event\listener
        tags:
            - { name: event.listener }

    phpbb.pages.controller:
        class: phpbb\pages\controller\main_controller
        arguments:
            - @controller.helper
            - @service_container
            - @template
            - @user
